[build-system]
requires = ["setuptools"]

[project]
name = "limnoria-etymology"
version = "0.0.0"
authors = [
    { name = "Stathis Xantinidis https://github.com/spithash" },
]
readme = "README.md"
dependencies = [
    "limnoria",
]
classifiers = [
    'Environment :: Plugins',
    'Programming Language :: Python :: 3',
    'Topic :: Communications :: Chat',
]

[project.entry-points.'limnoria.plugins']
Etymology = "limnoria_etymology"

[tool.setuptools.package-dir]
"limnoria_etymology" = "."

[tool.setuptools.package-data]
"limnoria_etymology" = ["locales/*.po"]
